// common
export const PAGE_SET_INFO = 'PAGE_SET_INFO'
export const SHOPPING_GET_NUM = 'SHOPPING_GET_NUM'
// 获取消息列表数据
export const MESSAGE_GET_LIST = 'MESSAGE_GET_LIST'
export const MESSAGE_LIST_CURRENTPAGE = 'MESSAGE_LIST_CURRENTPAGE'
// 我的
export const MESSAGE_GET_COUNTER = 'MESSAGE_GET_COUNTER'
export const CENTER_GET_DATA = 'CENTER_GET_DATA'
// user
export const LOGIN_IS_SUCCESS = 'LOGIN_IS_SUCCESS'
