// common
export const PAGE_SET_INFO = 'PAGE_SET_INFO'
// 获取消息列表数据
export const MESSAGE_GET_LIST = 'MESSAGE_GET_LIST'
export const MESSAGE_LIST_CURRENTPAGE = 'MESSAGE_LIST_CURRENTPAGE'
// 我的
export const MESSAGE_GET_COUNTER = 'MESSAGE_GET_COUNTER'

