// common
export const PAGE_SET_INFO = 'PAGE_SET_INFO'
export const SHOPPING_GET_NUM = 'SHOPPING_GET_NUM'
export const TOP_RIGHT_CLICK_FONT = 'TOP_RIGHT_CLICK_FONT'
export const GLOBAL_SET_LOADINNG = 'GLOBAL_SET_LOADINNG'
// 首页
export const INDEX_GET_DATA = 'INDEX_GET_DATA'
// 获取消息列表数据
export const MESSAGE_GET_LIST = 'MESSAGE_GET_LIST'
export const MESSAGE_LIST_CURRENTPAGE = 'MESSAGE_LIST_CURRENTPAGE'
// 购物车列表
export const SHOPPINGCART_GET_LIST = 'SHOPPINGCART_GET_LIST'
export const SHOPPINGCART_LIST_CURRENTPAGE = 'SHOPPINGCART_LIST_CURRENTPAGE'
export const SHOPPINGCART_SELECT_ALL = 'SHOPPINGCART_SELECT_ALL'
export const SHOPPINGCART_SELECT_ITEM = 'SHOPPINGCART_SELECT_ITEM'
export const SHOPPINGCART_DELETE_SELECT = 'SHOPPINGCART_DELETE_SELECT'
export const SHOPPINGCART_DELETE_ARRAY = 'SHOPPINGCART_DELETE_ARRAY'
export const CALCULATE_TOTAL_PRICE = 'CALCULATE_TOTAL_PRICE'
// 我的
export const MESSAGE_GET_COUNTER = 'MESSAGE_GET_COUNTER'
export const CENTER_GET_DATA = 'CENTER_GET_DATA'
// 我的收藏
export const COLLECT_GET_LIST = 'COLLECT_GET_LIST'
export const COLLECT_LIST_CURRENTPAGE = 'COLLECT_LIST_CURRENTPAGE'
export const SHOW_CHECKBOX = 'SHOW_CHECKBOX'
// user
export const LOGIN_IS_SUCCESS = 'LOGIN_IS_SUCCESS'
// 目的地
export const DESTINATION_GET_INDEX = 'DESTINATION_GET_INDEX'
